#!/bin/bash

printf '**BOOTSTRAPPING ANDREW NIJMEH"S NEW MACBOOK BOOK PRO'

echo "Installing homebrew".
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
