#!/bin/bash

printf '**BOOTSTRAPPING ANDREW NIJMEH"S NEW MACBOOK BOOK PRO'

xcode-select --install
sudo softwareupdate --install-rosetta

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew update
brew tap homebrew/cask-fonts
brew tap homebrew/autoupdate
brew tap homebrew/cask
brew tap hackclub/tap
brew tap homebrew/core
